### ISSUE TITLE
The LED in the Arduino UNO example does not blink

### ISSUE THREAD

**Issue by Nerzal** [tinygo-org/playground#10]
The LED in the Arduino UNO example does not blink in the browser. 
Tested at https://play.tinygo.org/ 

I am using Ubuntu 20.04 and a Firefox (latest version)

**Comment by aykevl** [comment]
Fixed it with https://github.com/tinygo-org/playground/commit/6da4487030f815ed317ce6553c1e10b927bc54a1.
