### ISSUE TITLE
v0.18 error on playground

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/playground#11]
```
TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function
```

**Comment by aykevl** [comment]
Yes, for that we need to update the server that serves play.tinygo.org. I believe that's served by Netlify? It is fixed in 9b3267f2128048a7c6c0e0175ee8474aa330b470 but needs to be deployed.

**Comment by deadprogram** [comment]
Committing  to `master` does the deployment. Hence now closing as it has been resolved. Thanks @aykevl

**Comment by aykevl** [comment]
Ah okay, thanks! That's good to know.
