### ISSUE TITLE
Error: "upstream request timeout" occurring on playground after clicking "Flash"

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/playground#7]
The error "upstream request timeout" is occurring frequently on the Playground website when trying to download code using the "Flash" button.

I do not have the same issue/slowness when compiling inside the web interface for the simulator.

**Comment by aykevl** [comment]
It seems to work for me, although it is also rather slow at the moment.

**Comment by deadprogram** [comment]
Might just be performance is too slow under current load? It used to be a lot faster...

**Comment by aykevl** [comment]
For which target was this the case?

> Might just be performance is too slow under current load?

Unlikely, it is little used. And even if there was a high load, GCP should just add more instances automatically.

There is a timeout of 20 seconds. I thought this was a reasonable upper limit, not expecting timeouts to happen. However, the samd-based boards are much slower to compile so probably are the reason why you're hitting a timeout.

**Comment by deadprogram** [comment]
OK that makes sense, as those were the only boards I actually tried, it seemed like a general slowdown vs. the performance of a new feature.

So you will up the timeout?

**Comment by aykevl** [comment]
Ok, updated to 30s. Hopefully that fixes it for now.

For the long term, the compiler should really be sped up (something I've been working on already for a looong time).

**Comment by deadprogram** [comment]
OK closing for now. Will reopen if needed.
