### ISSUE TITLE
I get an error when I try to run it locally

### ISSUE THREAD

**Issue by sago35** [tinygo-org/playground#9]
I get this message and I can't run it locally.

> LinkError: import object field 'syscall/js.finalizeRef' is not a Function

end:
windows10 pro 64bit
tinygo  64d51b215f63a3b178c6337ab252086d16003ff7

```
git clone --recursive https://github.com/tinygo-org/tinygo.git tinygo5
cd tinygo5
git checkout dev
make llvm-build
make
make gen-device
make wasi-libc
make release
```

**Comment by sago35** [comment]
![image](https://user-images.githubusercontent.com/9251039/83819068-e5c73680-a703-11ea-9c67-0cd94402a17d.png)

**Comment by aykevl** [comment]
Weird. Which Go version are you using? You could try using Go 1.13.

**Comment by sago35** [comment]
I'm using Go 1.14.3.
> go version go1.14.3 windows/amd64

Later, I'll try Go 1.13.

**Comment by aykevl** [comment]
This should be fixed. Is this still an issue?

**Comment by aykevl** [comment]
I assume this is fixed by now. If not, please reopen.
